package com.mx.opin.sadimiapp.main;

//import com.mx.opin.sadimi.dao.PersonalSeguridadDAO;
//import com.mx.opin.sadimi.model.PersonalSeguridad;
import com.mx.opin.sadimiapp.dao.impl.LoginDAOImpl;
import com.mx.opin.sadimiapp.model.PersonalSeguridad;
import javax.swing.JOptionPane;
import java.sql.*;
//import org.springframework.beans.factory.annotation.Autowired;

//import org.springframework.beans.factory.xml.XmlBeanFactory;
//import org.springframework.context.support.ClassPathXmlApplicationContext;
//import org.springframework.core.io.ClassPathResource;


public class venPrinc extends javax.swing.JFrame {

    static String nombreA;

    public venPrinc() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        idUser = new javax.swing.JTextField();
        passwordUser = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(102, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Tempus Sans ITC", 1, 80)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 0, 51));
        jLabel2.setText("PROTOTIPO");
        jLabel2.setMaximumSize(new java.awt.Dimension(700, 102));
        jPanel1.add(jLabel2);
        jLabel2.setBounds(30, 10, 550, 80);

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("User: ");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(160, 340, 70, 20);

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Password:");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(130, 370, 100, 23);

        idUser.setBackground(new java.awt.Color(255, 255, 255));
        idUser.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        idUser.setForeground(new java.awt.Color(0, 0, 0));
        idUser.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        idUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idUserActionPerformed(evt);
            }
        });
        jPanel1.add(idUser);
        idUser.setBounds(260, 340, 140, 23);

        passwordUser.setBackground(new java.awt.Color(255, 255, 255));
        passwordUser.setForeground(new java.awt.Color(0, 0, 0));
        passwordUser.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                passwordUserKeyPressed(evt);
            }
        });
        jPanel1.add(passwordUser);
        passwordUser.setBounds(260, 370, 140, 20);

        jButton1.setFont(new java.awt.Font("Bebas Neue", 1, 24)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 0, 0));
        jButton1.setText("Iniciar Sesion");
        jButton1.setAutoscrolls(true);
        jButton1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton1.setContentAreaFilled(false);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButton1.setFocusPainted(false);
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(190, 400, 150, 40);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mx/opin/sadimiapp/Img/escuela.png"))); // NOI18N
        jPanel1.add(jLabel6);
        jLabel6.setBounds(150, 0, 300, 400);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 528, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 455, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
//    ClassPathXmlApplicationContext context = new ClassPathXmlApplicationContext("spring4.xml");

    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        LoginDAOImpl loginDAOImpl = new LoginDAOImpl();
        
        String nom = idUser.getText();
        String pass = passwordUser.getText();

        if (!nom.isEmpty() || !pass.isEmpty()) {
//            PersonalSeguridad personalSeguridad = new PersonalSeguridad();
//            personalSeguridad = loginDAOImpl.login(nom, pass);
//            if (personalSeguridad != null) {
            if (nom.equals("admin") && pass.equals("admin")) {
                JOptionPane.showMessageDialog(null, "Correctos.");
                Opciones op = new Opciones();
                op.setVisible(true);
                op.setLocationRelativeTo(null);
                this.dispose();
            } else {
                JOptionPane.showMessageDialog(null, "NO Correctos.");
            }

        } else {
            JOptionPane.showMessageDialog(null, "Datos incorrectos, verifique nuevamente.");
        }
//        context.close();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void idUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idUserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idUserActionPerformed

    private void passwordUserKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_passwordUserKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordUserKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(venPrinc.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(venPrinc.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(venPrinc.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(venPrinc.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new venPrinc().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JTextField idUser;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    public javax.swing.JPasswordField passwordUser;
    // End of variables declaration//GEN-END:variables
}
